/* Com-layer glue for the body-domain routing.
 *
 * On a production ECU these functions are generated by the Com
 * configuration (Com_SendSignal / Com_ReceiveSignal + the I-PDU
 * group mapping). They are written out here so the full byte path
 *
 *   LIN bytes -> LinPack_Unpack* -> BodyRouting_OnLin*
 *   BodyRouting MainFunction -> Com_Send_* -> CanPack_Pack* -> CanIf
 *
 * is visible and host-testable end to end.
 */

#include "BodyRouting.h"
#include "LinPack.h"
#include "CanPack.h"
#include "Dem.h"

/* Lower-layer transmit, provided by CanIf (mocked on host). */
extern Std_ReturnType CanIf_GwTransmit(uint32 canId,
                                       const uint8 *bytes, uint16 len);

/* ------------------------------------------------------------------ *
 *  RX path: called from the PduR/LinIf RX indication for the two
 *  gateway LIN PDUs. Malformed frames are dropped and counted.
 * ------------------------------------------------------------------ */

void BodyRoutingCom_LinRxIndication(uint8 linPduId,
                                    const uint8 *bytes, uint16 len)
{
    switch (linPduId) {
        case LIN_PDU_MSW_TO_VCU: {
            LinSig_MSWToVCU sig;
            if (LinPack_UnpackMSWToVCU(bytes, len, &sig) == E_OK) {
                BodyRouting_OnLinMSWToVCU(&sig);
            } else {
                Dem_ReportErrorStatus(DEM_EVT_PDUR_LEN, DEM_EVENT_STATUS_FAILED);
            }
            break;
        }
        case LIN_PDU_HANDLE_TO_VCU: {
            LinSig_HandleToVCU sig;
            if (LinPack_UnpackHandleToVCU(bytes, len, &sig) == E_OK) {
                BodyRouting_OnLinHandleToVCU(&sig);
            } else {
                Dem_ReportErrorStatus(DEM_EVT_PDUR_LEN, DEM_EVENT_STATUS_FAILED);
            }
            break;
        }
        default:
            /* Not a gateway LIN PDU -- ignore (allow-list semantics). */
            break;
    }
}

/* ------------------------------------------------------------------ *
 *  TX path: BodyRouting's Com_Send_* hooks. Pack and hand to CanIf.
 *  A pack failure means a programming error upstream (range guard
 *  in BodyRouting), so it is reported, never silently swallowed.
 * ------------------------------------------------------------------ */

void Com_Send_CCVS_VCU(const CanSig_CCVS_VCU *s)
{
    uint8 buf[CAN_FRAME_SIZE];
    if (CanPack_PackCCVS_VCU(s, buf, CAN_FRAME_SIZE) == E_OK) {
        (void)CanIf_GwTransmit(CANID_CCVS_VCU, buf, CAN_FRAME_SIZE);
    } else {
        Dem_ReportErrorStatus(DEM_EVT_PDUR_LEN, DEM_EVENT_STATUS_FAILED);
    }
}

void Com_Send_TSC1_VDR(const CanSig_TSC1_VDR *s)
{
    uint8 buf[CAN_FRAME_SIZE];
    if (CanPack_PackTSC1(s, buf, CAN_FRAME_SIZE) == E_OK) {
        (void)CanIf_GwTransmit(CANID_TSC1_VDR, buf, CAN_FRAME_SIZE);
    } else {
        Dem_ReportErrorStatus(DEM_EVT_PDUR_LEN, DEM_EVENT_STATUS_FAILED);
    }
}

void Com_Send_TSC1_DR(const CanSig_TSC1_VDR *s)
{
    /* Engine-brake variant: same PGN/layout, different target. The
     * CAN id differs only in destination/source addressing. */
    uint8 buf[CAN_FRAME_SIZE];
    if (CanPack_PackTSC1(s, buf, CAN_FRAME_SIZE) == E_OK) {
        (void)CanIf_GwTransmit(0x0C000027u, buf, CAN_FRAME_SIZE);
    } else {
        Dem_ReportErrorStatus(DEM_EVT_PDUR_LEN, DEM_EVENT_STATUS_FAILED);
    }
}

void Com_Send_TC1(const CanSig_TC1 *s)
{
    uint8 buf[CAN_FRAME_SIZE];
    if (CanPack_PackTC1(s, buf, CAN_FRAME_SIZE) == E_OK) {
        (void)CanIf_GwTransmit(CANID_TC1_VCU, buf, CAN_FRAME_SIZE);
    } else {
        Dem_ReportErrorStatus(DEM_EVT_PDUR_LEN, DEM_EVENT_STATUS_FAILED);
    }
}
