/* Schedule Manager exclusive-area for BodyRouting.
 *
 * On AUTOSAR Classic: generated by SchM from the module description.
 * On NuttX: backed by a POSIX pthread_mutex owned by BodyRouting.c.
 *
 * The mutex is declared inside BodyRouting.c (static) and accessed
 * here via the two lock/unlock functions that BodyRouting.c exports.
 * This mirrors the AUTOSAR pattern where the SchM stub calls into
 * the module's own OS-abstraction layer.                             */

#ifndef SCHM_BODYROUTING_H
#define SCHM_BODYROUTING_H

#include "Compiler.h"
#include "Std_Types.h"

/* Provided by BodyRouting.c — do NOT call these directly outside of
 * this header; use the SchM_ macros instead.                          */
extern FUNC(void, BODYROUTING_CODE) BodyRouting_EnterLinRxMutex(void);
extern FUNC(void, BODYROUTING_CODE) BodyRouting_ExitLinRxMutex(void);

LOCAL_INLINE FUNC(void, BODYROUTING_CODE) SchM_Enter_BodyRouting_LinRxData(void)
{
    BodyRouting_EnterLinRxMutex();
}

LOCAL_INLINE FUNC(void, BODYROUTING_CODE) SchM_Exit_BodyRouting_LinRxData(void)
{
    BodyRouting_ExitLinRxMutex();
}

#endif
